name = "TimeDag"
uuid = "91963e24-6e66-4132-aeb8-436d9f37dbc7"
authors = ["Invenia Technical Computing Corporation"]
version = "0.1.11"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AssociativeWindowAggregation = "444271a7-5434-4a02-b82b-0e30a9223c60"
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TeaFiles = "c40ccc24-2f2a-4785-85cd-06e8176bc8e2"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
AbstractTrees = "0.3, 0.4"
AssociativeWindowAggregation = "0.2, 0.3"
Bijections = "0.1"
Combinatorics = "1"
DataStructures = "0.18"
LightGraphs = "1"
PrettyTables = "1"
RecipesBase = "1"
StaticArrays = "1"
Tables = "1"
TeaFiles = "0.1"
TimeZones = "1"
julia = "1.6"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Combinatorics", "DataFrames", "Random", "Test"]
